### ISSUE TITLE
Importing relaxed bodies for setting up giant impact initial conditions

### ISSUE THREAD

**Issue by ajacksonastro** [srbonilla/WoMa#10]
If I have done a short relaxation simulation for my target and impactor bodies is there a convenient way to import the relaxed bodies from the SWIFT HDF5 dumps at the end of the relaxation for the purposes of setting up the initial conditions for the impact?  Unless I am missing something, the ParticlePlanet class does not seem to have a load function.

**Comment by Francyrad** [comment]
Hello. Some years ago I had a similar issue. I found this guide which is been super exhaustive 

https://github.com/JingyaoDOU/SWIFT_share_public

There is a Jupiter Notebook which explains you what to write exactly in you python script to Join 2 HDF5 files to create an impact I.C

I only suggest you to use the constants of the actual Swift repository instead of the ones of the guide when setting up your simulation in Swift, because your simulation may go to slow.

**Comment by ajacksonastro** [comment]
That was very helpful, thanks.  It seems to have worked, except that when I try to run SWIFT it gives me an error that "not all particles are within the specified domain".  I'm not sure why, as the box size is set to 100 Earth Radii and when I save the combined particle data it says the minimum and maximum positions are well within that (no more than +/- 5 Earth Radii).  Any ideas?

**Comment by ajacksonastro** [comment]
That was very helpful, thanks. It seems to have worked, except that when I try to run SWIFT it gives me an error that "not all particles are within the specified domain". I'm not sure why, as the box size is set to 100 Earth Radii and when I save the combined particle data it says the minimum and maximum positions are well within that (no more than +/- 5 Earth Radii). Any ideas?

**Comment by ajacksonastro** [comment]
That was very helpful, thanks. It seems to have worked, except that when I try to run SWIFT it gives me an error that "not all particles are within the specified domain". I'm not sure why, as the box size is set to 100 Earth Radii and when I save the combined particle data it says the minimum and maximum positions are well within that (no more than +/- 5 Earth Radii). Any ideas?

**Comment by Francyrad** [comment]
Can you please share here the script that you use to join particles and the script that you use to inizialize your simulation? 

Please use: ``` between your code

```
Your code 
```

**Comment by jkeger** [comment]
Hi!  The reason we didn't make bespoke load functions for the output of settling simulations is simply because you'd need the same kind of loading code to analyse the output of any swift simulation, so we recommend using those same tools regardless of the situation. (For more general information and details about the snapshot format, see https://swift.strw.leidenuniv.nl/docs/Snapshots/index.html)

To that end, there are two main options I'd recommend. One is using `swiftsimio` (https://swiftsimio.readthedocs.io/en/latest/), the python package we've developed for SWIFT (although I personally don't actually use it because it was released after I'd already got used to the second option). The second is using `h5py` to manually load the data, e.g.
```
with h5py.File(snapshot_file_path, "r") as f:
    N_particles = f["Header"].attrs["NumPart_Total"][0]
    positions = f["PartType0/Coordinates"][()]
    # etc...
```

Eithr way, once you have loaded the settled data, you should then be able to combine and save them as described in the last section of the woma tutorial notebook. Check out the code for the `woma.save_particle_data()` function in `woma/misc/io.py` to see the actual `h5py` code.

And whatever loading method you use, you can then do the same thing for analysing the outputs of production simulations. See for example the `plot_solution.py` scripts in many of SWIFT's `swiftsim/examples/` folders for loading in the HDF5 data for analysis. Whether it's a settling, impact, or any other kind of simulation, you can load the outputs into python in the same way.

Edit: swiftsimio is also useful because it automatically deals carefully and correctly with the units. If you use h5py manually, then if it helps you can also load in the units yourself as they are saved to the hdf5 header by swift, e.g. `f["Units"].attrs["Unit length in cgs (U_L)"]`

**Comment by jkeger** [comment]
> I only suggest you to use the constants of the actual Swift repository instead of the ones of the guide when setting up your simulation in Swift, because your simulation may go to slow.

In swift the internal units are not a particularly big deal, but in general it is a good idea to set whatever internal units will keep your particle parameter values at not-extreme orders of magnitude. However, I think you have to go to very very large or tiny magnitudes for this to cause any problems.

**Comment by jkeger** [comment]
> That was very helpful, thanks. It seems to have worked, except that when I try to run SWIFT it gives me an error that "not all particles are within the specified domain". I'm not sure why, as the box size is set to 100 Earth Radii and when I save the combined particle data it says the minimum and maximum positions are well within that (no more than +/- 5 Earth Radii). Any ideas?

Have you got your coordinate origin in the center of your box? SWIFT simulation volumes have (0, 0, 0) as the corner, so the centre of the box is (1, 1, 1)*box_size/2, and all particle positions should be >0 to be in the box.

You can always inspect the HDF5 file for the initial conditions directly with tools like `hdfview` that can be very useful for catching any problems, as well as `swiftsimio` and `h5py`. Running swift in debug mode by configuring with `--enable-debugging-checks`  is also a helpful thing to check in many situations.

**Comment by jkeger** [comment]
Hope some of that helps, but please let me know how it goes! And thank you Francyrad for the extra support :)

**Comment by ajacksonastro** [comment]
Thanks for the help.  The issue seems to have been that the particles were in the corner of the box, not the centre, as jkeger suggested.  Now that I've fixed that it seems to be working.  Also thanks for the tips on `swiftsimio`

**Comment by jkeger** [comment]
You're welcome, thanks for your interest in the code!

**Comment by ajacksonastro** [comment]
Probably more of a SWIFT issue, but I thought I would ask here if anyone has any ideas.  It seems like the simulation I am running is being very inefficient.  I set it to use 16 cores, but the majority of the time only two or three are actually doing anything with the others sitting idle, leading to dead times of 10000-100000 ms per step.  I'm wondering if I've set something up wrong.  I'm trying to do a canonical Moon-forming impact at 1e6 particles in the target as a test, and I've just copied earth_impact.yml exactly, except for setting the units so that Earth mass =1 and Earth radius =1, and extending the integration time to 20 hours.  When I ran the relaxation simulations this wasn't an issue, so I'm wondering if I did something wrong in setting up the combined simulation.  Plotting the output from the dumps so far looks normal, but maybe I'm missing something.

**Comment by Francyrad** [comment]
Please share your .yml here. 

How much big is the box radii in the simulation? 

What command do you use to start swift?

**Comment by ajacksonastro** [comment]
I've attached the .yml below (I changed the ending to .txt so GitHub would allow me to upload it).  It's almost identical to earth_impact.yml from the example.  The box is 100 Earth Radii on each side.

To start SWIFT I used the command `[path to swift]/swift -s -G -t 16 canonical.yml 2>&1 | tee canonical.log` copied from run.sh in the example with the filename changed.
[canonical.txt](https://github.com/srbonilla/WoMa/files/11410792/canonical.txt)

**Comment by jkeger** [comment]
Hi Alan,

That does sound like something's up!

I would recommend shifting this to our SWIFT gitter discussion rooms, since we have multiple members of our team who (when they have time) can respond and help you investigate (https://app.gitter.im/#/room/#swiftsim_Lobby:gitter.im , also linked from the swift homepage).

When you do, the three first questions I'd ask are: (1) do you get this issue from running the EarthImpact example itself? (2) Have you tried running after configuring with `--enable-debugging-checks`? That's worth doing just in case something detectible is wrong, but don't use it for speed tests as it is slower. (3) What system and architecture are you running on?

So maybe include that info with a post there. I'll help if I can, but I have some travel this week so it might not be immediate, and if it is a system-related issue then others on our team have more extensive experience with that kind of thing.

Cheers,

Jacob

**Comment by Francyrad** [comment]
@ajacksonastro your simulation is very slow because you did a little bit of confusion with the following values:

```
InternalUnitSystem:
    UnitMass_in_cgs:        5.972e27    # Sets Earth mass = 1
    UnitLength_in_cgs:      6.371e8     # Sets Earth radius = 1
    UnitVelocity_in_cgs:    6.371e8     # Sets time in seconds
    UnitCurrent_in_cgs:     1           # Amperes
    UnitTemp_in_cgs:        1           # Kelvin
    
    
    h_max:              1.2  
    
```

These values are going to be ok for a relaxation, but when you do a collision, particles will spread out and they will search neighbours. Because they cannot find them, the simulation will impossibly slow down.
The point is that h_max it's a value that depends on the values that you give to the simulation, that is to say:

UnitMass, Unitlenght and velocity in cgs

The values that you gave are not ok for the hmax values of 1.2. You should change hmax to another value, or you can just change the values according to this:

```
InternalUnitSystem:
    UnitMass_in_cgs:        1e27        # Sets Earth mass = 5.972
    UnitLength_in_cgs:      1e8         # Sets Earth radius = 6.371
    UnitVelocity_in_cgs:    1e8         # Sets time in seconds
    UnitCurrent_in_cgs:     1           # Amperes
    UnitTemp_in_cgs:        1           # Kelvin
```

And hmax can stay 1.2. I verified that the simulation will go much faster with these values because the particles that will go too much far away will act as ballistic projectiles. Obviously your simulation will not go faster like a relaxation, but it will take "human times".

In the guide that i sent to you there is written to use the first values (earth mass, earth radius etc.). It is not necessary in post processing because you can convert these values (1e8 m) in earth radii with a python script later using a specify swiftisimio function.

Please, let us know if things go better.
Francesco

**Comment by jkeger** [comment]
Thanks Francesco for the suggestion, you might well be right that the large h_max is causing a slow-down, that's definitely worth checking. For completeness though, some of those details aren't quite correct. I suppose the reasons may not matter if the result is the same haha, but since you mentioned it, the slowdown that we get with large h_max is not because of the large-h particles themselves trying to find neighbours. It is more related to the cell heirarchy and how cells are allowed to subdivide or not to load-balance their tasks. That's why it could explain why you'd see only a few active threads, because a few cells locked to large local maximum h aren't able to share out their work in the normal way.

(Incidentally, we have actually fixed this slowdown issue with large h_max! But that's on a non-master branch that is still undergoing some final testing to iron out a few very-rare bugs. So hopefully that will be merge-able to master before too long for much better balancing and speed in those situations.)

Anyway! One quick question is whether your runtime changes as the simulation evolves. If it starts of running fine until the bodies collide, and then it slows down, then h_max likely is the issue, and trying h_max = 0.5 or 0.2 R_Earth or some value will probably fix it. If not, then it is probably something else.

If it helps for deciding what h_max to use for your science applications, you can also think about the minimum density this implies for a particle with zero neighbours. It's important to note that, while this imposes a not-very-physical aspect on a simulation, some SPH codes that do not use an h_max or equivalent can easily reach non-physical regimes when particles have very large h (where the SPH assumptions of a continuous fluid and only small changes to material properties like density at the h scale), but in that case you won't be as clearly alerted to it. 

Note also, that when particles hit h_max, they do not immediately "act as ballistic projectiles". That would be the case when a particle has *zero* neighbours, but particles can still have many neighbours while being at h_max. For instance, if a particle wants e.g. 48 neighbours by default, then if it moves too far away, it will hit h=h_max but still have e.g. 35 neighbours, then say 15 if it moves further, etc. This may cause issues with the thermodynamics in some cases, which adds to the general importance of doing convergence and other numerical tests for science results.

**Comment by Francyrad** [comment]
Thank you for your clarifications. I hope that the bug will be fixed soon. I hope in the fix because i noticed a tiny slowdown in my simulations:

e.g: if i could run 1kk particles simulation in 24 hours (27 hours of simulation), now it take like  1 day and half or 2.

Since we're talking about it, I also take the opportunity to ask you if the values ​​I use in my .yml are acceptable or can be improved. the purpose of my simulations is to see where the very long distance particles go. I am therefore forced to use a box of 10,000 terrestrial radii.


```
InternalUnitSystem:
    UnitMass_in_cgs:        1e27        # Sets Earth mass = 5.972
    UnitLength_in_cgs:      1e8         # Sets Earth radius = 6.371
    UnitVelocity_in_cgs:    1e8         # Sets time in seconds
    UnitCurrent_in_cgs:     1           # Amperes
    UnitTemp_in_cgs:        1           # Kelvin

SPH:
    resolution_eta:     1.2348          # Target smoothing length in units of the mean inter-particle separation (1.2348 == 48Ngbs with the cubic spline kernel).
    delta_neighbours:   0.1             # The tolerance for the targetted number of neighbours.
    CFL_condition:      0.2             # Courant-Friedrich-Levy condition for time integration.
    h_max:              1.2             # Maximal allowed smoothing length (in internal units).
    viscosity_alpha:    1.5             # Override for the initial value of the artificial viscosity.

```
What do you think? Can I improve something?
I wish you a good job
Francesco

**Comment by ajacksonastro** [comment]
Ah, thank you both for spotting that.  I checked back and indeed, the simulation was running fairly quickly until the bodies started to collide, at which point the dead time ballooned.  I reduced the h_max to 0.2 Earth Radii, so keeping roughly the same value proportionally as it was in the EarthImpact example and it is now behaving much better.  The dead time did still rise when the bodies started colliding, but only to a few thousand ms (having been a few hundred to ~1000 ms before impact).

Thanks also for pointing me to the SWIFT gitter discussion room.  I've joined that so I can ask future questions there!

**Comment by jkeger** [comment]
Great! 

Francesco thanks for the questions, I've sent you an email so we can continue chatting in more detail there :)

**Comment by Francyrad** [comment]
Hello, are there news about the post-impact slowness of the code regarding hmax and the size of the box?

**Comment by jkeger** [comment]
Not at the moment. Progress there is relying on rare-bug tests and fixes that other SWIFT members will be looking into, but sadly not until some of their other projects are completed, I think. I'll continue to promote its priority as best I can.
